{{- if .Values.webhook.createSelfSignedCertificate }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "scylla-operator.certificateName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ include "scylla-operator.webhookServiceName" . }}.{{ .Release.Namespace }}.svc
  issuerRef:
    kind: Issuer
    name: {{ printf "%s-selfsigned-issuer" (include "scylla-operator.fullname" .) }}
  secretName: {{ include "scylla-operator.certificateSecretName" . }}
{{- end }}
