{{- range .Values.scyllaClusters }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "scylla.name" . }}
  namespace: {{ include "scylla.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scyllacluster-member
subjects:
- kind: ServiceAccount
  name: {{ include "scylla.serviceAccountName" . }}
  namespace: {{ include "scylla.namespace" . }}
{{- end }}
