{{- range .Values.scyllaClusters }}
{{- if dig "serviceAccount" "create" true . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scylla.serviceAccountName" . }}
  namespace: {{ include "scylla.namespace" . }}
  labels:
  {{- include "scylla.labels" . | nindent 4 }}
    {{- with (dig "serviceAccount" "annotations" (dict) .) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
