{{- if .Values.webhook.createSelfSignedCertificate }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ printf "%s-selfsigned-issuer" (include "scylla-operator.fullname" .) }}
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end }}
