apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "scylla-operator.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook-server
      app.kubernetes.io/instance: {{ .Release.Name }}
